sudo: false

env:
  global:
  - PATH="$HOME/.local/bin/:$PATH"

addons:
  apt:
    packages:
    - inkscape

cache:
  directories:
  - '$HOME/.stack'

before_install:
- 'curl -Lo stack.tar.gz https://get.haskellstack.org/stable/linux-x86_64.tar.gz'
- 'tar xzf stack.tar.gz'
- 'mkdir -p "$HOME/.local/bin"'
- 'cp stack-*-linux-x86_64/stack "$HOME/.local/bin/"'

script:
- 'bash deploy/build.sh'
- 'bash deploy/deploy.sh'
